### ISSUE TITLE
[Major] UI Problem on IE9 (img attached)

### ISSUE THREAD

**Issue by joyzoursky** [oursky/oursky-site#30]
![screen shot 2015-07-06 at 12 32 09 pm](https://cloud.githubusercontent.com/assets/12539486/8515739/5658e7f6-23db-11e5-9fb5-b5990d5876f4.png)
![screen shot 2015-07-06 at 12 33 15 pm](https://cloud.githubusercontent.com/assets/12539486/8515740/576458a6-23db-11e5-9dd1-8fed838a404c.png)
![screen shot 2015-07-06 at 12 35 18 pm](https://cloud.githubusercontent.com/assets/12539486/8515957/45465832-23df-11e5-8758-064a893ebd67.png)

**Comment by koskosm** [comment]
For this I recommend we use this https://github.com/TurnWheel/jReject

**Comment by koskosm** [comment]
http://googleappsupdates.blogspot.hk/2013/11/end-of-support-for-internet-explorer-9.html

**Comment by joyzoursky** [comment]
Yes, I see this on current website, don't know if it is the same plugin.
![screen shot 2015-07-06 at 7 12 51 pm](https://cloud.githubusercontent.com/assets/12539486/8521110/28c7e69c-2413-11e5-9ad3-26e3d1f6f8b1.png)

**Comment by carmenlau** [comment]
Added alert in IE9.
