### ISSUE TITLE
[Minor] [Dropdown Menu] User should not be able to scroll things behind the dropdown menu (may cause flashing in mobile)

### ISSUE THREAD

**Issue by joyzoursky** [oursky/oursky-site#44]

**Comment by jylau3** [comment]
Still can reproduce this issue in mobile safari
1. Click on drop down menu and scroll  the menu to bottom and scroll up
2. User can scroll the page under the drop down menu 

![img_1383](https://cloud.githubusercontent.com/assets/8348924/13423549/826f9350-dfd6-11e5-87d3-d244b54484d9.PNG)
