### ISSUE TITLE
Enquiry form doesn't with mouse click / tap

### ISSUE THREAD

**Issue by chpapa** [oursky/oursky-site#57]
It just give a flash, doesn't submit the form, also don't show error.

However, enter a form would works.

**Comment by chpapa** [comment]
It seems if we remove the optimizely submit code things work again. Maybe we should just do that.

**Comment by rickmak** [comment]
I think after adding tap, the optimizely web editor will no longer works with the form. @CYBAI let me know how to let the biz people do A/B testing?

**Comment by CYBAI** [comment]
I will check how to use it with form appropriately.

**Comment by hosiupan** [comment]
We are not running any active ab testing now. We can skip it if too trouble

**Comment by CYBAI** [comment]
@hosiupan I've created an optimizely for test; besides, I found that other developers also have this issue when using optimizely with form submission.
